[versions]
junit-jupiter-engine = "5.10.2"
ktor = "2.3.7"
exposed = "0.52.0"
ksp = "1.9.22-1.0.17"
koin = "3.5.6"
koin-ksp = "1.3.1"
kotlin = "1.9.22"


[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }

