name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.20' # Adjust to match your Go version




      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 92.38.48.85
          username: root
          password: qG5hZ7bC1j
          script: |
            cd Dostap-Backend
            git pull origin main
            pkill dostapp
            go build -o dostapp ./cmd/main.go
            ./dostapp & disown 
            lsof -i :3001
            echo "Hello"
            exit
